const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const [exe,fixture]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/expansion-observer-'));let n=0;
const native=p=>p.replace(/^([A-Za-z]):/,(_,d)=>'/mnt/'+d.toLowerCase()).replaceAll('\\','/');
function call(args,r){const f=path.join(root,`r${++n}.json`);if(r)fs.writeFileSync(f,JSON.stringify(r));const p=spawnSync('wsl.exe',['--exec',exe,'--workspace',native(path.join(root,'state')),...args,...(r?['--request',native(f)]:[])],{encoding:'utf8',timeout:60000,maxBuffer:4194304});assert.ifError(p.error);assert([0,3].includes(p.status),p.stdout+p.stderr);const result=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,`o${n}.json`),JSON.stringify(result,null,2));return result;}
call(['project','create','--name','observer']);const t=call(['target','import','--project','observer','--file',native(path.resolve(fixture))]);
const inv=call(['harness','create'],{project:'observer',target_id:t.id,objective:'Compare source-backed CoreCLR baseline and instrumentation',required_facts:['bounded observer comparison'],owner:{mode:'external',name:'observer fixture'},workbench_mutations:true,budget:{max_actions:2,wall_ms:120000,output_bytes:262144},runtime_execution:{trusted_host_execution:true,targets:[{target_id:t.id,file:native(path.resolve(fixture))}],engines:['io']}});
const action=call(['harness','propose'],{project:'observer',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'pair',proposal:{gap:'observer behavior',prediction:'same output under tracing',expected_evidence:'paired receipts',fallback:'retain uncertainty'},request:{backend:'workbench',operation:'experiment.run',arguments:{engine:'io',prediction:'source fixture output stable under EventPipe',cases:[{label:'baseline',managed_trace:false,timeout_ms:10000},{label:'observed',managed_trace:true,timeout_ms:10000}]}}});
const result=call(['harness','run'],{project:'observer',id:inv.id,owner_token:inv.owner_token,expected_revision:action.investigation_revision,action_id:action.id});const record=call(['knowledge','show','--project','observer','--id',result.result.knowledge_ids[0]]);
assert.equal(record.body.comparison.observer_changed,true);assert.equal(record.body.comparison.complete,true);assert.equal(record.body.comparison.output_changed,false);assert.equal(record.body.comparison.acceptance_proven,false);assert(JSON.stringify(record.body).includes('indago-observed-exception'));
console.log(JSON.stringify({passed:true,root,comparison:record.body.comparison}));
