const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const [exe,image]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/guest-transfer-'));let n=0;
const native=p=>p.replace(/^([A-Za-z]):/,(_,d)=>'/mnt/'+d.toLowerCase()).replaceAll('\\','/');
function call(args,r,reject=false){const f=path.join(root,`r${++n}.json`);if(r)fs.writeFileSync(f,JSON.stringify(r));const p=spawnSync('wsl.exe',['--exec',exe,'--workspace',native(path.join(root,'state')),...args,...(r?['--request',native(f)]:[])],{encoding:'utf8',timeout:45000,maxBuffer:4194304});assert.ifError(p.error);if(reject){assert(![0,3].includes(p.status),p.stdout);return;}assert.equal(p.status,0,p.stdout+p.stderr);const result=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,`o${n}.json`),JSON.stringify(result,null,2));return result;}
call(['project','create','--name','transfer']);const boot=call(['target','import','--project','transfer','--file',image]);const input=Buffer.alloc(512);input[0]=84;const file=path.join(root,'input.raw');fs.writeFileSync(file,input);const transfer=call(['target','import','--project','transfer','--file',native(file)]);
const profile=call(['guest','create'],{image:{path:image,sha256:boot.artifact_sha256},transfer:{path:native(file),sha256:transfer.artifact_sha256},machine:'pc-i440fx-10.2',accelerator:'kvm',trusted_guest:true});
const create={project:'transfer',target_id:boot.id,objective:'Read an admitted byte through a guest read-only disk',required_facts:['observed byte'],owner:{mode:'external',name:'transfer fixture'},workbench_mutations:true,guest_profiles:[profile.id],budget:{max_actions:1,wall_ms:90000,output_bytes:262144}};
const denied=call(['harness','create'],create),allowed=call(['harness','create'],{...create,scope:{target_ids:[boot.id,transfer.id]}});
function propose(inv,reject=false){return call(['harness','propose'],{project:'transfer',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'transfer',proposal:{gap:'read-only input delivery',prediction:'first byte reaches serial',expected_evidence:'guest output',fallback:'partial'},request:{backend:'workbench',operation:'guest.run',arguments:{body:{profile:profile.id,actions:[{operation:'observe',duration_ms:700}]}}}},reject);}
propose(denied,true);const a=propose(allowed);const run=call(['harness','run'],{project:'transfer',id:allowed.id,owner_token:allowed.owner_token,expected_revision:a.investigation_revision,action_id:a.id});assert.equal(run.result.guest.status,'completed',JSON.stringify(run));const record=call(['knowledge','show','--project','transfer','--id',run.result.knowledge_ids[0]]);assert.equal(record.body.serial.bytes,1);assert.equal(record.body.serial.sha256,crypto.createHash('sha256').update('T').digest('hex'));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),transfer.artifact_sha256);
fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({passed:true,root,receipt:record.body},null,2));console.log(JSON.stringify({passed:true,root}));
