cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/PackedPayload.cmake")
set(INDAGO_ENABLE_PAYLOAD_COMPRESSION ON)
file(SHA256 "${RAW_FILE}" _raw_sha)
file(SIZE "${RAW_FILE}" _raw_size)
indago_select_payload("${RAW_FILE}" "${_raw_sha}" "${_raw_size}" _file _size _compressed)
if(EXPECT_COMPRESSED)
    if(NOT _compressed OR NOT _size LESS _raw_size OR _file STREQUAL RAW_FILE)
        message(FATAL_ERROR "Verified packed representation not selected")
    endif()
else()
    if(_compressed OR NOT _file STREQUAL RAW_FILE OR NOT _size EQUAL _raw_size)
        message(FATAL_ERROR "Raw fallback changed its source or size")
    endif()
endif()
