cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/StableGeneratedFile.cmake")
if(NOT DEFINED TEST_OUTPUT OR NOT IS_ABSOLUTE "${TEST_OUTPUT}")
    message(FATAL_ERROR "An explicit absolute TEST_OUTPUT directory is required")
endif()
set(output "${TEST_OUTPUT}/literal.txt")
set(content [=[literal ${UNEXPANDED};@UNEXPANDED@;$<CONFIG>;"quoted"\path
second line
]=])
indago_write_if_different("${output}" "${content}")
file(READ "${output}" actual)
if(NOT "${actual}" STREQUAL "${content}")
    message(FATAL_ERROR "Generated content was interpreted or changed")
endif()
file(TIMESTAMP "${output}" before "%s" UTC)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
indago_write_if_different("${output}" "${content}")
file(TIMESTAMP "${output}" unchanged "%s" UTC)
if(NOT before STREQUAL unchanged)
    message(FATAL_ERROR "Unchanged generated input was touched")
endif()
indago_write_if_different("${output}" "${content}changed")
file(READ "${output}" actual)
file(TIMESTAMP "${output}" changed "%s" UTC)
if(NOT "${actual}" STREQUAL "${content}changed" OR changed STREQUAL before)
    message(FATAL_ERROR "Changed generated input was not updated")
endif()
message(STATUS "Stable generation passed: literal bytes, unchanged timestamps, changed-content invalidation")
