const fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const [exe,fixture]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/task5-harness-engine-')),workspace=path.join(root,'state');let count=0;
function app(args,req){const f=path.join(root,`request-${++count}.json`);if(req)fs.writeFileSync(f,JSON.stringify(req));const p=spawnSync(exe,['--workspace',workspace,...args,...(req?['--request',f]:[])],{encoding:'utf8',timeout:50000,maxBuffer:4*1024**2});if(p.error)throw p.error;const r=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,`response-${count}.json`),JSON.stringify(r,null,2));if(![0,3].includes(p.status))throw Error(JSON.stringify(r));return r;}
app(['project','create','--name','engines']);const t=app(['target','import','--project','engines','--file',path.resolve(fixture)]);
const inv=app(['harness','create'],{project:'engines',target_id:t.id,objective:'Observe entry, capture, reanalyze with a ready companion',required_facts:['Capture provenance'],owner:{mode:'external',name:'trusted fixture'},workbench_mutations:true,budget:{max_actions:2,wall_ms:100000,output_bytes:262144},runtime_execution:{trusted_host_execution:true,targets:[{target_id:t.id,file:path.resolve(fixture)}],engines:['debugger']}});
const action=app(['harness','propose'],{project:'engines',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'capture',proposal:{gap:'entry state',prediction:'capture available',expected_evidence:'native capture and reanalysis',fallback:'retain partial'},request:{backend:'workbench',operation:'experiment.run',arguments:{engine:'debugger',prediction:'Companion ready before main',companions:[{target_id:t.id,argv:['--companion'],ready:{file:'ready',hex:'5245414459'}}],cases:[{label:'capture',argv:['--fixture'],input_hex:'7965730a',files:{payload:'626f756e64'},environment:{EXPERIMENT_VALUE:'explicit'}}]}}});
const result=app(['harness','run'],{project:'engines',id:inv.id,owner_token:inv.owner_token,expected_revision:action.investigation_revision,action_id:action.id});
const record=app(['knowledge','show','--project','engines','--id',result.result.knowledge_ids[0]]);const c=record.body.cases[0];
const refreshed=app(['harness','show','--project','engines','--id',inv.id]);
const cleanup=app(['harness','propose'],{project:'engines',id:inv.id,owner_token:inv.owner_token,expected_revision:refreshed.revision,key:'cleanup',proposal:{gap:'owned session lifecycle',prediction:'sessions terminal',expected_evidence:'cleanup receipt',fallback:'retain uncertainty'},request:{backend:'workbench',operation:'experiment.cleanup',arguments:{action_id:action.id}}});
const cleaned=app(['harness','run'],{project:'engines',id:inv.id,owner_token:inv.owner_token,expected_revision:cleanup.investigation_revision,action_id:cleanup.id});
const passed=c.companions[0]?.readiness?.observed===true&&c.planned_breakpoint_reached===true&&c.observations.some(x=>x.operation==='capture'&&x.result.status==='completed')&&c.observations.some(x=>x.operation==='reanalyze'&&x.result.status==='completed')&&!record.body.outcome_unknown&&cleaned.result.cleanup.status==='completed';
fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({root,passed,body:record.body},null,2));console.log(JSON.stringify({root,passed,status:record.body.status,diagnostic:c.diagnostic},null,2));process.exitCode=passed?0:1;
