const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const [exe,app,dependency]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/task7-cli-'));let sequence=0;
const linux=exe.startsWith('wsl:'),native=p=>linux?p.replace(/^([A-Za-z]):/,(_,d)=>'/mnt/'+d.toLowerCase()).replaceAll('\\','/'):p;
function call(args,r){const f=path.join(root,'request-'+(++sequence)+'.json');if(r){if(r.catalogue)r.catalogue=native(r.catalogue);fs.writeFileSync(f,JSON.stringify(r));}const argv=['--workspace',native(path.join(root,'state')),...args.map(native),...(r?['--request',native(f)]:[])];const c=spawnSync(linux?'wsl.exe':exe,linux?['--exec',exe.slice(4),...argv]:argv,{encoding:'utf8',timeout:60000,maxBuffer:4*1024*1024});assert.ifError(c.error);assert([0,3].includes(c.status),c.stdout+c.stderr);const o=JSON.parse(c.stdout);fs.writeFileSync(path.join(root,'response-'+sequence+'.json'),JSON.stringify(o,null,2));return o;}
call(['project','create','--name','managed']);
const target=call(['target','import','--project','managed','--file',path.resolve(app)]),dep=call(['target','import','--project','managed','--file',path.resolve(dependency)]);
const route=call(['target','route','--project','managed','--id',target.id]);assert.equal(route.kind,'managed_pe');assert.equal(route.automatic_execution,false);
const request={project:'managed',backend:'ilspy',target_id:target.id,operation:'references',arguments:{dependencies:[dep.id]}};
const references=call(['action','run'],request);assert.equal(references.status,'completed');assert(references.data.references.some(r=>r.target_artifact_sha256===dep.artifact_sha256));
const members=call(['action','run'],{...request,operation:'member_refs'});assert(members.data.member_refs.some(r=>r.name==='Add'&&r.target_artifact_sha256===dep.artifact_sha256));
const memberLinks=call(['index','relations','--project','managed','--backend','ilspy','--kind','managed_member_reference']);assert(memberLinks.records.some(r=>r.target_location.artifact_sha256===dep.artifact_sha256));
const relations=call(['index','relations','--project','managed','--backend','ilspy','--kind','managed_assembly_dependency']);assert(relations.records.some(r=>r.target_location.artifact_sha256===dep.artifact_sha256));
const inv=call(['harness','create'],{project:'managed',target_id:target.id,objective:'Static managed scope check',required_facts:['metadata'],owner:{mode:'external',name:'task7 contract'}});
const scopedRoute=call(['harness','read'],{project:'managed',id:inv.id,family:'artifact',operation:'route',request:{}});assert.equal(scopedRoute.kind,'managed_pe');
let rejected=false;try{call(['harness','propose'],{project:'managed',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'foreign-dependency',proposal:{gap:'dependency',prediction:'resolved',expected_evidence:'metadata',fallback:'partial'},request});}catch(e){assert.match(e.message,/managed dependency outside investigation scope/);rejected=true;}assert(rejected);
const coverage=call(['benchmark','coverage'],{catalogue:path.resolve('config/flare-on-2014-2024.catalogue.json')});assert.equal(coverage.denominator,116);assert.equal(coverage.all_formats_supported,false);assert(coverage.families.android_package.length>0);assert(coverage.families.verilog.length>0);
fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({passed:true,root,route,managed_relationships:relations.records.length,catalogue_sha256:coverage.catalogue_sha256,families:coverage.families},null,2));console.log(JSON.stringify({passed:true,root,managed_relationships:relations.records.length},null,2));
