const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const [exe,fixture]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/task7-harness-trace-'));let n=0;
function call(args,r){const f=path.join(root,`r${++n}.json`);if(r)fs.writeFileSync(f,JSON.stringify(r));const p=spawnSync(exe,['--workspace',path.join(root,'state'),...args,...(r?['--request',f]:[])],{encoding:'utf8',timeout:50000,maxBuffer:4194304});assert.ifError(p.error);assert([0,3].includes(p.status),p.stdout+p.stderr);const result=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,`o${n}.json`),JSON.stringify(result,null,2));return result;}
call(['project','create','--name','trace']);const t=call(['target','import','--project','trace','--file',path.resolve(fixture)]);
const inv=call(['harness','create'],{project:'trace',target_id:t.id,objective:'Observe source-backed managed exception without an acceptance claim',required_facts:['runtime observations'],owner:{mode:'external',name:'task7 fixture'},workbench_mutations:true,budget:{max_actions:2,wall_ms:100000,output_bytes:262144},runtime_execution:{trusted_host_execution:true,targets:[{target_id:t.id,file:path.resolve(fixture)}],engines:['io']}});
const action=call(['harness','propose'],{project:'trace',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'trace',proposal:{gap:'managed events',prediction:'fixture exception observed',expected_evidence:'EventPipe trace',fallback:'partial'},request:{backend:'workbench',operation:'experiment.run',arguments:{engine:'io',managed_trace:true,prediction:'Managed method and exception',cases:[{label:'observed',input_hex:'',environment:{}}]}}});
const result=call(['harness','run'],{project:'trace',id:inv.id,owner_token:inv.owner_token,expected_revision:action.investigation_revision,action_id:action.id});const record=call(['knowledge','show','--project','trace','--id',result.result.knowledge_ids[0]]);
const raw=JSON.stringify(record);assert(raw.includes('managed_exception'));assert(raw.includes('trace_artifact_sha256'));assert(raw.includes('indago-observed-exception'));
console.log(JSON.stringify({passed:true,root}));
