// Source-backed live read -> copy -> compare -> native solve -> original replay.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const [exe,fixture,model]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/task6-input-loop-')),workspace=path.join(root,'state');let n=0;
const linux=exe.startsWith('wsl:');const nativePath=p=>linux?p.replace(/^([A-Za-z]):[\\/]/,(_,d)=>'/mnt/'+d.toLowerCase()+'/').replaceAll('\\','/'):p;
const targetFile=linux?fixture:path.resolve(fixture);
function app(args,r){const f=path.join(root,`request-${++n}.json`);if(r)fs.writeFileSync(f,JSON.stringify(r));const commandArgs=['--workspace',nativePath(workspace),...args,...(r?['--request',nativePath(f)]:[])];const p=spawnSync(linux?'wsl.exe':exe,linux?['--exec',exe.slice(4),...commandArgs]:commandArgs,{encoding:'utf8',timeout:model?240000:60000,maxBuffer:8*1024**2});if(p.error)throw p.error;let out;try{out=JSON.parse(p.stdout)}catch{throw Error(p.stdout+p.stderr)}fs.writeFileSync(path.join(root,`response-${n}.json`),JSON.stringify(out,null,2));if(![0,3].includes(p.status))throw Error(JSON.stringify(out));return out;}
app(['project','create','--name','input']);const target=app(['target','import','--project','input','--file',targetFile]);
const oracle=path.join(root,'oracle.json');fs.writeFileSync(oracle,JSON.stringify({schema:'indago.io-oracle.v1',artifact_sha256:target.artifact_sha256||target.sha256,fact:'Original fixture accepts candidate',stdout_hex:'50415353',exit_code:0,negative_input_hex:'3030303030303030'}));
// The oracle contains no answer bytes; only the original program's observable predicate.
const owner=model?{mode:'builtin',name:'task6-local',profile:{provider:'local',model,endpoint:'http://127.0.0.1:1234/v1/chat/completions',context_tokens:65536,output_tokens:2048,generation_ms:60000}}:{mode:'external',name:'source-backed test'};
const objective=model?'Plan first, then demonstrate a bounded native input solve on this trusted fixture. Use argv ["--solve-input"] for every case. Observe with workbench experiment.run engine frida recipe input and baseline input_hex 3030303030303030. The answer is not supplied: native input_solutions will contain solver_candidate references. Replay both equality candidate and native counterexample using engine io, the same argv and baseline input, and case.solver_candidate references from the observation result. The operator oracle is already configured. Report observed original-target acceptance and negative rejection with experiment receipt citations, finish partial, and never claim an independently graded challenge solve. No static analysis is needed for this smoke test.':'Observe input mapping and invert a comparison';
const inv=app(['harness','create'],{project:'input',target_id:target.id,objective,required_facts:['original-target acceptance'],owner,workbench_mutations:true,budget:{max_actions:model?6:3,wall_ms:240000,output_bytes:1048576},runtime_execution:{trusted_host_execution:true,targets:[{target_id:target.id,file:targetFile,acceptance_oracle:nativePath(oracle)}],engines:['frida','io']}});
if(model) {
  const result=app(['harness','explore'],{project:'input',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,allow_inference:true,recipe:'general',max_generations:6});
  fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({root,status:result.status,usage:result.controller_usage},null,2));process.exit(0);
}
function experiment(key,args){const state=app(['harness','show','--project','input','--id',inv.id]);const action=app(['harness','propose'],{project:'input',id:inv.id,owner_token:inv.owner_token,expected_revision:state.revision,key,proposal:{gap:key,prediction:'native evidence reduces uncertainty',expected_evidence:'bounded original-target receipts',fallback:'retain partial'},request:{backend:'workbench',operation:'experiment.run',arguments:args}});const result=app(['harness','run'],{project:'input',id:inv.id,owner_token:inv.owner_token,expected_revision:action.investigation_revision,action_id:action.id});return app(['knowledge','show','--project','input','--id',result.result.knowledge_ids[0]]);}
const observed=experiment('observe',{engine:'frida',recipe:'input',prediction:'stdin reaches comparison through copy',cases:[{label:'seed',argv:['--solve-input'],input_hex:'3030303030303030'}]});
const current=observed.body.cases[0],solution=current.input_solutions?.find(s=>s.status==='completed');
if(!solution)throw Error(JSON.stringify({root,case:current}));
const cases=[0,1].map((branch)=>({label:branch?'counterexample':'candidate',argv:['--solve-input'],input_hex:'3030303030303030',solver_candidate:{session:current.session,observation:solution.id,terminal:0,branch,candidate:0}}));
const replay=experiment('replay',{engine:'io',prediction:'equality candidate accepted, counterexample rejected',cases});
const a=replay.body.cases[0].state.observation.data,b=replay.body.cases[1].state.observation.data;
const passed=a.complete&&b.complete&&a.accepted===true&&a.output_hex==='50415353'&&b.output_hex==='4641494c'&&solution.data.caller_binding.status==='completed'&&solution.data.results[0].branches.every(b=>b.caller_branch);
fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({root,passed,observation:observed,solution,replay},null,2));console.log(JSON.stringify({root,passed,input_provenance:solution.data.provenance,candidate:replay.body.cases[0].input.input_hex,accepted:a.accepted,negative_output:b.output_hex},null,2));process.exitCode=passed?0:1;
