// Source-built, inert parser inputs. No benchmark execution or answer material.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const [exe]=process.argv.slice(2),root=fs.mkdtempSync(path.resolve('out/task7-artifacts-'));let n=0;
const linux=exe.startsWith('wsl:'),native=p=>linux?p.replace(/^([A-Za-z]):/,(_,d)=>'/mnt/'+d.toLowerCase()).replaceAll('\\','/'):p;
function call(args,r,ok=true){const file=path.join(root,`r${++n}.json`);if(r)fs.writeFileSync(file,JSON.stringify(r));const argv=['--workspace',native(path.join(root,'state')),...args.map(native),...(r?['--request',native(file)]:[])];const p=spawnSync(linux?'wsl.exe':exe,linux?['--exec',exe.slice(4),...argv]:argv,{encoding:'utf8',timeout:30000,maxBuffer:1048576});assert.ifError(p.error);if(ok)assert([0,3].includes(p.status),p.stdout+p.stderr);const result=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,`o${n}.json`),JSON.stringify(result,null,2));return result;}
call(['project','create','--name','formats']);
function artifact(name,bytes){const file=path.join(root,name);fs.writeFileSync(file,bytes);return call(['target','import','--project','formats','--file',file]);}
function inspect(t,arguments_={}){return call(['action','run'],{project:'formats',target_id:t.id,backend:'ilspy',operation:'artifact',arguments:arguments_});}
const source=artifact('helper.js',Buffer.from('const answer = 6 * 7;\n'));assert(inspect(source).data.text.includes('6 * 7'));
const wasm=artifact('one.wasm',Buffer.from('0061736d010000000105016000017f03020100070701036f6e6500000a0601040041010b','hex'));const wat=inspect(wasm);assert.equal(wat.status,'completed');assert(wat.data.text.includes('i32.const 1'));
// Stored ZIP built with canonical CRC and central directory; path is a literal member, never a host path.
const name=Buffer.from('../inert.js'),content=Buffer.from('const marker = 42;');let crc=0xffffffff;for(const b of content){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;
const local=Buffer.alloc(30),central=Buffer.alloc(46),end=Buffer.alloc(22);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(content.length,18);local.writeUInt32LE(content.length,22);local.writeUInt16LE(name.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(content.length,20);central.writeUInt32LE(content.length,24);central.writeUInt16LE(name.length,28);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(central.length+name.length,12);end.writeUInt32LE(local.length+name.length+content.length,16);
const zip=artifact('package.zip',Buffer.concat([local,name,content,central,name,end]));const listing=inspect(zip);assert.equal(listing.data.items[0].name,name.toString());assert.equal(inspect(zip,{entry:name.toString()}).data.content_hex,content.toString('hex'));
const derived=call(['transform','run'],{project:'formats',artifact:zip.artifact_sha256,spec:{method:'container_member',entry:name.toString()}});assert.equal(derived.artifact_sha256,crypto.createHash('sha256').update(content).digest('hex'));
assert.equal(inspect({id:derived.target_id}).data.text,content.toString());assert(!fs.existsSync(path.join(root,'inert.js')));
const inv=call(['harness','create'],{project:'formats',target_id:zip.id,objective:'Derive one bounded member',required_facts:['child bytes'],owner:{mode:'external',name:'fixture'},workbench_mutations:true,derived_artifacts:{max_artifacts:1,max_bytes:1048576}});
const proposed=call(['harness','propose'],{project:'formats',id:inv.id,owner_token:inv.owner_token,expected_revision:inv.revision,key:'extract',proposal:{gap:'child',prediction:'exact content',expected_evidence:'derived identity',fallback:'fail closed'},request:{backend:'workbench',operation:'transform.run',arguments:{spec:{method:'container_member',entry:name.toString()}}}});
const executed=call(['harness','run'],{project:'formats',id:inv.id,owner_token:inv.owner_token,expected_revision:proposed.investigation_revision,action_id:proposed.id});assert(JSON.stringify(executed).includes(derived.artifact_sha256));
const ole=artifact('fixture.ole',fs.readFileSync('out/task7-doc-fixtures/fixture.ole'));assert.equal(inspect(ole).data.items[0].name,'inert');assert.equal(Buffer.from(inspect(ole,{entry:'inert'}).data.content_hex,'hex').toString(),'indago OLE marker');
let pdf='%PDF-1.4\n',offsets=[0];const objects=['<< /Type /Catalog /Pages 2 0 R /OpenAction 5 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream','<< /S /JavaScript /JS (inert-marker) >>'];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
const document=artifact('fixture.pdf',Buffer.from(pdf));assert.equal(inspect(document).data.page_count,1);assert(inspect(document,{entry:'5:0'}).data.object_text.includes('inert-marker'));assert.equal(inspect(document).data.active_content_executed,false);
fs.writeFileSync(path.join(root,'summary.json'),JSON.stringify({passed:true,source:true,wasm:true,zip:true,derived:derived.artifact_sha256}));console.log(JSON.stringify({passed:true,root}));
