cmake_minimum_required(VERSION 3.24)
project(indago_frida C)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
if(NOT FRIDA_DEVKIT)
  message(FATAL_ERROR "Specify pinned FRIDA_DEVKIT directory")
endif()
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/recipes.js" RECIPE_SOURCE)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/recipes.js")
string(REPLACE "\\" "\\\\" RECIPE_SOURCE "${RECIPE_SOURCE}")
string(REPLACE "\"" "\\\"" RECIPE_SOURCE "${RECIPE_SOURCE}")
string(REPLACE "\n" "\\n\"\n\"" RECIPE_SOURCE "${RECIPE_SOURCE}")
set(RECIPE_SOURCE "\"${RECIPE_SOURCE}\"")
configure_file(recipes.h.in recipes.h @ONLY)
add_executable(indago_frida_host host.c)
target_include_directories(indago_frida_host PRIVATE "${FRIDA_DEVKIT}" "${CMAKE_CURRENT_BINARY_DIR}")
target_link_directories(indago_frida_host PRIVATE "${FRIDA_DEVKIT}")
target_link_libraries(indago_frida_host PRIVATE frida-core)
if(WIN32)
  target_link_libraries(indago_frida_host PRIVATE setupapi)
else()
  target_link_libraries(indago_frida_host PRIVATE dl m rt resolv pthread)
  target_link_options(indago_frida_host PRIVATE -Wl,--export-dynamic -Wl,--gc-sections)
endif()
