import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {enabled,finalText,Progress,Investigation,environmentPrompt} from '../improvements.mjs';
import {phpLiteral,strings,pngTail} from '../helper.mjs';
test('features can be isolated',()=>{assert(enabled({features:['state']},'state'));assert(!enabled({features:['state']},'surface'));assert(!enabled({features:[]},'state'));});
test('plain remains an unenhanced reference unless explicitly overridden',()=>{assert(!enabled({mode:'plain'},'environment'));assert(enabled({mode:'plain',features:['environment']},'environment'));});
test('environment guidance retains exact entry points and the native Windows path contract',()=>{const p=environmentPrompt({python:{path:'runtime/python',sha256:'private-version-hash'},archive:{unavailable:true}});assert(p.includes('runtime/python'));assert(!p.includes('private-version-hash'));assert(p.includes('unavailable'));if(process.platform==='win32'){assert(p.includes('case-relative'));assert(p.includes('Do not use /tmp'));}});
test('tool syntax is not an answer',()=>{assert(!finalText('<tool_call><function=bash>'));assert(!finalText(''));assert(finalText('Unresolved: comparison branch not established.'));});
test('successful identical calls stagnate; timeout change is not progress',()=>{const p=new Progress();p.observe('bash',{command:'dump'},'bytes');p.observe('bash',{command:'dump'},'bytes');assert(p.blocked('bash',{command:'dump',timeout:40}));p.observe('write',{},'ok');assert(!p.blocked('bash',{command:'dump'}));});
test('compact state is bounded and artifact-scoped',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'indago-state-'));const s=new Investigation(path.join(dir,'state.json'),'a');s.update({facts:Array(12).fill('fact'),candidate:'candidate',obligation:'verify branch'});assert.equal(s.data.facts.length,5);s.update({artifact:'b'});assert.equal(s.data.candidate,null);assert.equal(s.data.facts.length,0);fs.rmSync(dir,{recursive:true});});
test('PHP literal examples preserve language semantics',()=>{assert.equal(phpLiteral(String.raw`\x41\101`),'AA');assert.equal(phpLiteral(String.raw`\97`),String.raw`\97`);assert.equal(phpLiteral(String.raw`\n`,"'"),String.raw`\n`);assert.equal(phpLiteral(String.raw`a\'b`,"'"),"a'b");assert.equal(phpLiteral(String.raw`\$`),'$');});
test('strings give byte locations and bounded lines',()=>{const r=strings(Buffer.from('hello\0world!'));assert.equal(r[0].offset,0);assert.equal(r[1].offset,6);assert.equal(r[1].text,'world!');});
const chunk=(type,data)=>{const header=Buffer.alloc(8);header.writeUInt32BE(data.length);header.write(type,4);return Buffer.concat([header,data,Buffer.alloc(4)]);};
const framed=()=>Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',Buffer.alloc(13)),chunk('IDAT',Buffer.from('IEND is data, not a boundary')),chunk('IEND',Buffer.alloc(0))]);
test('PNG tail uses chunk boundaries, preserves bytes and declares verification limits',()=>{const image=framed(),payload=Buffer.from([0,255,42,3]);const r=pngTail(Buffer.concat([image,payload]));assert.equal(r.offset,image.length);assert.deepEqual(r.bytes,payload);assert.match(r.validation,/not verified/);assert.equal(pngTail(image).bytes.length,0);});
test('PNG malformed framing fails closed',()=>{assert.throws(()=>pngTail(Buffer.from('IEND')));assert.throws(()=>pngTail(framed().subarray(0,20)));const bad=framed();bad.writeUInt32BE(0xffffffff,33);assert.throws(()=>pngTail(bad));});
