# Source-built runtime payloads are prepared by tools/build-runtime-engines.*.
# No downloads take place in the product or during its normal CMake build.
include("${CMAKE_CURRENT_LIST_DIR}/StableGeneratedFile.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/PackedPayload.cmake")
option(INDAGO_ENABLE_PAYLOAD_COMPRESSION "Use explicitly staged lossless payload representations" ON)
set(INDAGO_PACKED_PAYLOAD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/out/payload-packed" CACHE PATH "Content-addressed, verified packed payloads")
if(INDAGO_ENABLE_PAYLOAD_COMPRESSION)
    file(GLOB _packed_metadata CONFIGURE_DEPENDS "${INDAGO_PACKED_PAYLOAD_DIR}/*.json")
endif()
set(_files "")
set(_names "")
foreach(_notice LICENSE COPYING)
    list(APPEND _files "${CMAKE_CURRENT_SOURCE_DIR}/vendor/zstd/upstream/${_notice}")
    list(APPEND _names "licenses/zstd/${_notice}")
endforeach()
list(APPEND _files "${CMAKE_CURRENT_SOURCE_DIR}/vendor/zstd/PROVENANCE.md")
list(APPEND _names "licenses/zstd/PROVENANCE.md")
if(TARGET LIEF::LIEF)
    foreach(_notice LICENSE PROVENANCE.md THIRD-PARTY.md dependency-archives.json Boost-1.0.txt json-LICENSE.MIT fmt-LICENSE.txt)
        list(APPEND _files "${CMAKE_CURRENT_SOURCE_DIR}/vendor/lief/${_notice}")
        list(APPEND _names "licenses/lief/${_notice}")
    endforeach()
    file(GLOB_RECURSE _lief_notices CONFIGURE_DEPENDS LIST_DIRECTORIES false "${CMAKE_CURRENT_SOURCE_DIR}/vendor/lief/notices/*")
    foreach(_file IN LISTS _lief_notices)
        file(RELATIVE_PATH _notice "${CMAKE_CURRENT_SOURCE_DIR}/vendor/lief" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "licenses/lief/${_notice}")
    endforeach()
endif()
if(WIN32)
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR CMAKE_GENERATOR_PLATFORM MATCHES "ARM")
        message(FATAL_ERROR "The Windows host is x64; target processes may be x86 or x64")
    endif()
    enable_language(RC)
    target_link_options(indago PRIVATE /DELAYLOAD:dbghelp.dll)
    target_link_libraries(indago PRIVATE delayimp)
    set(_dbg "${CMAKE_CURRENT_SOURCE_DIR}/vendor/dbgeng")
    target_include_directories(indago_core PRIVATE "${_dbg}/build/native/inc")
    foreach(_name dbgeng.dll dbghelp.dll dbgcore.dll dbgmodel.dll msdia140.dll)
        list(APPEND _files "${_dbg}/content/amd64/${_name}")
        list(APPEND _names "dbgeng/${_name}")
    endforeach()
    list(APPEND _files "${_dbg}/LICENSE.rtf")
    list(APPEND _names "dbgeng/LICENSE.rtf")
    set(_os windows)
else()
    enable_language(ASM)
    set(_os linux)
    list(APPEND _files "${CMAKE_CURRENT_SOURCE_DIR}/vendor/openssl/NOTICE.txt" "${CMAKE_CURRENT_SOURCE_DIR}/vendor/openssl/Apache-2.0.txt")
    list(APPEND _names "licenses/openssl/NOTICE.txt" "licenses/openssl/Apache-2.0.txt")
    foreach(_notice jitterentropy zlib zstd)
        list(APPEND _files "${CMAKE_CURRENT_SOURCE_DIR}/vendor/openssl/${_notice}-NOTICE.txt")
        list(APPEND _names "licenses/openssl/${_notice}-NOTICE.txt")
    endforeach()
endif()
set(INDAGO_RUNTIME_PAYLOAD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/out/runtime-payload/${_os}" CACHE PATH "Privately bundled source-built runtime engines")
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/dynamorio")
    foreach(_bits 32 64)
        if(WIN32)
            set(_required "bin${_bits}/indago_dr_host.exe" "bin${_bits}/drinjectlib.dll" "bin${_bits}/drconfiglib.dll" "lib${_bits}/indago_dr_client.dll" "lib${_bits}/release/dynamorio.dll")
        else()
            set(_required "bin${_bits}/indago_dr_host" "lib${_bits}/libindago_dr_client.so" "lib${_bits}/release/libdynamorio.so")
        endif()
        foreach(_file IN LISTS _required)
            if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/dynamorio/${_file}")
                message(FATAL_ERROR "Incomplete runtime payload: ${_file}; rerun tools/build-runtime-engines")
            endif()
        endforeach()
    endforeach()
    file(GLOB_RECURSE _dr_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/dynamorio/*")
    foreach(_file IN LISTS _dr_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_DYNAMORIO=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_DYNAMORIO=0)
endif()
set(_header "#pragma once\n#include <cstddef>\nstruct PayloadEntry { unsigned id; const char* name; const char* sha; const unsigned char* data; std::size_t size; std::size_t stored_size; bool compressed; };\n")
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/frida")
    if(WIN32)
        set(_frida_host indago_frida_host.exe)
    else()
        set(_frida_host indago_frida_host)
    endif()
    if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/frida/${_frida_host}")
        message(FATAL_ERROR "Incomplete Frida payload")
    endif()
    file(GLOB _frida_files CONFIGURE_DEPENDS "${INDAGO_RUNTIME_PAYLOAD_DIR}/frida/*")
    foreach(_file IN LISTS _frida_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_FRIDA=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_FRIDA=0)
endif()
set(_entries "")
if(NOT WIN32 AND EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/replay/bin/rr")
    foreach(_required bin/rr_exec_stub bin/rr_exec_stub_32 lib/rr/librrpreload.so lib/rr/librrpreload_32.so lib/rr/librrpage.so lib/rr/librrpage_32.so PROVENANCE.md LICENSE)
        if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/replay/${_required}")
            message(FATAL_ERROR "Incomplete rr payload: ${_required}")
        endif()
    endforeach()
    file(GLOB_RECURSE _rr_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/replay/*")
    foreach(_file IN LISTS _rr_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_RR=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_RR=0)
endif()
if(WIN32)
    set(_packet_worker tshark.exe)
else()
    set(_packet_worker tshark)
endif()
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/network/${_packet_worker}")
    file(GLOB_RECURSE _network_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/network/*")
    foreach(_file IN LISTS _network_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_WIRESHARK=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_WIRESHARK=0)
endif()
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/enrichment")
    if(WIN32)
        set(_enrichment_executables capa.exe floss.exe)
    else()
        set(_enrichment_executables capa floss)
    endif()
    foreach(_required IN LISTS _enrichment_executables)
        if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/enrichment/${_required}")
            message(FATAL_ERROR "Incomplete enrichment payload: ${_required}")
        endif()
    endforeach()
    foreach(_required capa-LICENSE.txt floss-LICENSE.txt PROVENANCE.md releases.json)
        if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/enrichment/${_required}")
            message(FATAL_ERROR "Missing enrichment notice: ${_required}")
        endif()
    endforeach()
    file(GLOB_RECURSE _enrichment_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/enrichment/*")
    foreach(_file IN LISTS _enrichment_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_ENRICHMENT=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_ENRICHMENT=0)
endif()
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/ilspy")
    if(WIN32)
        set(_ilspy_host indago_ilspy_worker.exe)
    else()
        set(_ilspy_host indago_ilspy_worker)
    endif()
    foreach(_required "${_ilspy_host}" "indago_ilspy_worker.dll" "indago_ilspy_worker.runtimeconfig.json" "ICSharpCode.Decompiler.dll" "ILSpy-LICENSE.txt" "dotnet-LICENSE.TXT" "dotnet-THIRD-PARTY-NOTICES.TXT" "packages.lock.json")
        if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/ilspy/${_required}")
            message(FATAL_ERROR "Incomplete ILSpy payload: ${_required}; run tools/build-ilspy.ps1")
        endif()
    endforeach()
    file(GLOB_RECURSE _ilspy_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/ilspy/*")
    foreach(_file IN LISTS _ilspy_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_ILSPY=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_ILSPY=0)
endif()
option(INDAGO_ALLOW_UNSTAGED_GDB "Allow a Linux native-core build without the private GDB payload" OFF)
if(NOT WIN32 AND (EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/gdb/bin/gdb" OR NOT INDAGO_ALLOW_UNSTAGED_GDB))
    if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/gdb/bin/gdb")
        message(FATAL_ERROR "Private GDB required on Linux; run tools/build-gdb.sh")
    endif()
    file(GLOB_RECURSE _gdb_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/gdb/*")
    foreach(_file IN LISTS _gdb_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
endif()
if(EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/ghidra")
    if(WIN32)
        set(_gh_native "distribution/Ghidra/Features/Decompiler/os/win_x86_64/decompile.exe")
        set(_gh_java "java/bin/java.exe")
    else()
        set(_gh_native "distribution/Ghidra/Features/Decompiler/os/linux_x86_64/decompile")
        set(_gh_java "java/bin/java")
    endif()
    foreach(_required "${_gh_native}" "${_gh_java}" "distribution/Ghidra/application.properties" "distribution/Ghidra/Framework/Utility/lib/Utility.jar" "java/release")
        if(NOT EXISTS "${INDAGO_RUNTIME_PAYLOAD_DIR}/ghidra/${_required}")
            message(FATAL_ERROR "Incomplete Ghidra payload: ${_required}; run tools/bundle-ghidra")
        endif()
    endforeach()
    file(GLOB_RECURSE _gh_files CONFIGURE_DEPENDS LIST_DIRECTORIES false "${INDAGO_RUNTIME_PAYLOAD_DIR}/ghidra/*")
    foreach(_file IN LISTS _gh_files)
        file(RELATIVE_PATH _name "${INDAGO_RUNTIME_PAYLOAD_DIR}" "${_file}")
        list(APPEND _files "${_file}")
        list(APPEND _names "${_name}")
    endforeach()
    file(GLOB _scripts CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/workers/ghidra/scripts/*.java")
    foreach(_file IN LISTS _scripts)
        get_filename_component(_name "${_file}" NAME)
        list(APPEND _files "${_file}")
        list(APPEND _names "ghidra/scripts/${_name}")
    endforeach()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_GHIDRA=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_GHIDRA=0)
endif()
set(_source "")
set(INDAGO_BUNDLE_PROFILE "runtime" CACHE STRING "Bundled engine profile: runtime or full")
set_property(CACHE INDAGO_BUNDLE_PROFILE PROPERTY STRINGS runtime full)
if(NOT INDAGO_BUNDLE_PROFILE STREQUAL "runtime" AND NOT INDAGO_BUNDLE_PROFILE STREQUAL "full")
    message(FATAL_ERROR "INDAGO_BUNDLE_PROFILE must be runtime or full")
endif()
set(_omitted_bytes 0)
set(_included_bytes 0)
set(_expanded_bytes 0)
set(_compressed_count 0)
set(_omitted_count 0)
set(_identity "")
set(_embedded_inputs "")
set(_id 201)
foreach(_file _name IN ZIP_LISTS _files _names)
    file(SIZE "${_file}" _size)
    set(_omit false)
    if(INDAGO_BUNDLE_PROFILE STREQUAL "runtime")
        # jmods are for constructing new Java runtimes, not running javac or
        # DecompInterface. Retain lib/modules, javac, sources and all notices.
        if(_name MATCHES "^ghidra/java/jmods/")
            set(_omit true)
        endif()
        if(_name MATCHES "^ghidra/distribution/.*/os/([^/]+)/")
            set(_native_os "${CMAKE_MATCH_1}")
            if(WIN32 AND NOT _native_os STREQUAL "win_x86_64")
                set(_omit true)
            elseif(NOT WIN32 AND NOT _native_os STREQUAL "linux_x86_64")
                set(_omit true)
            endif()
        endif()
    endif()
    if(_omit)
        math(EXPR _omitted_bytes "${_omitted_bytes}+${_size}")
        math(EXPR _omitted_count "${_omitted_count}+1")
        continue()
    endif()
    file(SHA256 "${_file}" _sha)
    indago_select_payload("${_file}" "${_sha}" "${_size}" _stored_file _stored_size _compressed)
    math(EXPR _included_bytes "${_included_bytes}+${_stored_size}")
    math(EXPR _expanded_bytes "${_expanded_bytes}+${_size}")
    if(_compressed)
        math(EXPR _compressed_count "${_compressed_count}+1")
    endif()
    list(APPEND _embedded_inputs "${_stored_file}")
    string(APPEND _identity "${_name}:${_sha}\n")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")
    if(WIN32)
        string(APPEND _source "${_id} RCDATA \"${_stored_file}\"\n")
        string(APPEND _entries "{${_id}, \"${_name}\", \"${_sha}\", nullptr, ${_size}, ${_stored_size}, ${_compressed}},\n")
    else()
        string(APPEND _source ".section .rodata\n.global payload_${_id}_begin\n.global payload_${_id}_end\npayload_${_id}_begin:\n.incbin \"${_stored_file}\"\npayload_${_id}_end:\n")
        string(APPEND _header "extern \"C\" const unsigned char payload_${_id}_begin[], payload_${_id}_end[];\n")
        string(APPEND _entries "{${_id}, \"${_name}\", \"${_sha}\", payload_${_id}_begin, ${_size}, static_cast<std::size_t>(payload_${_id}_end-payload_${_id}_begin), ${_compressed}},\n")
    endif()
    math(EXPR _id "${_id}+1")
endforeach()
indago_write_if_different("${CMAKE_CURRENT_BINARY_DIR}/generated/bundle-profile.json" "{\"profile\":\"${INDAGO_BUNDLE_PROFILE}\",\"included_bytes\":${_included_bytes},\"expanded_bytes\":${_expanded_bytes},\"compressed_files\":${_compressed_count},\"omitted_bytes\":${_omitted_bytes},\"omitted_files\":${_omitted_count},\"policy\":\"lossless staged compression; omit Java runtime-construction modules and foreign-OS native helpers; retain runtime, compiler, source archives and notices\"}\n")
string(SHA256 _bundle_sha "${_identity}")
string(APPEND _header "static const PayloadEntry engine_payload[] = {\n${_entries}{0,nullptr,nullptr,nullptr,0,0,false}};\nstatic constexpr auto engine_bundle_sha = \"${_bundle_sha}\";\n")
indago_write_if_different("${CMAKE_CURRENT_BINARY_DIR}/generated/engine_payload.hpp" "${_header}")
if(WIN32)
    indago_write_if_different("${CMAKE_CURRENT_BINARY_DIR}/generated/engines.rc" "${_source}")
    target_sources(indago PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated/engines.rc")
else()
    string(APPEND _source ".section .note.GNU-stack,\"\",@progbits\n")
    indago_write_if_different("${CMAKE_CURRENT_BINARY_DIR}/generated/engines.S" "${_source}")
    # .incbin is not a C/C++ include and compiler depfiles do not track it.
    # Content-stable assembly still needs rebuilding when a referenced payload
    # changes, even when its path and length are identical.
    set_property(SOURCE "${CMAKE_CURRENT_BINARY_DIR}/generated/engines.S"
        APPEND PROPERTY OBJECT_DEPENDS "${_embedded_inputs}")
    target_sources(indago_core PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated/engines.S")
endif()
