if(WIN32)
    set(_lief_platform windows)
else()
    set(_lief_platform linux)
endif()
set(INDAGO_LIEF_SDK "${CMAKE_CURRENT_SOURCE_DIR}/out/lief-sdk/${_lief_platform}" CACHE PATH "Pinned LIEF 1.0.0 static SDK")
if(EXISTS "${INDAGO_LIEF_SDK}/lib/cmake/LIEF/LIEFConfig.cmake")
    find_package(LIEF 1.0.0 EXACT CONFIG REQUIRED COMPONENTS STATIC
        PATHS "${INDAGO_LIEF_SDK}/lib/cmake/LIEF" NO_DEFAULT_PATH)
    target_link_libraries(indago_core PUBLIC LIEF::LIEF)
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_LIEF=1)
else()
    target_compile_definitions(indago_core PUBLIC INDAGO_HAS_LIEF=0)
endif()
