# Select an explicitly staged, round-trip-verified representation. Source files
# and raw hashes remain authoritative; absent packed metadata falls back to raw.
function(indago_select_payload source raw_sha raw_size selected_file selected_size selected_codec)
    set(_file "${source}")
    set(_size "${raw_size}")
    set(_codec false)
    set(_metadata "${INDAGO_PACKED_PAYLOAD_DIR}/${raw_sha}.json")
    if(INDAGO_ENABLE_PAYLOAD_COMPRESSION AND EXISTS "${_metadata}")
        file(SIZE "${_metadata}" _metadata_size)
        if(_metadata_size GREATER 4096 OR IS_SYMLINK "${_metadata}")
            message(FATAL_ERROR "Invalid packed payload metadata: ${_metadata}")
        endif()
        file(READ "${_metadata}" _manifest)
        foreach(_field schema codec raw_sha256 raw_bytes stored_sha256 stored_bytes roundtrip_verified)
            string(JSON _${_field} ERROR_VARIABLE _error GET "${_manifest}" "${_field}")
            if(_error)
                message(FATAL_ERROR "Invalid packed payload ${_field}: ${_metadata}")
            endif()
        endforeach()
        if(NOT _schema STREQUAL "indago.packed-payload.v1" OR NOT _codec STREQUAL "zstd"
           OR NOT _raw_sha256 STREQUAL "${raw_sha}" OR NOT _raw_bytes STREQUAL "${raw_size}"
           OR NOT _stored_bytes MATCHES "^[0-9]+$" OR NOT _roundtrip_verified)
            message(FATAL_ERROR "Packed payload source identity mismatch: ${source}")
        endif()
        set(_file "${INDAGO_PACKED_PAYLOAD_DIR}/${raw_sha}.zst")
        if(NOT EXISTS "${_file}" OR IS_SYMLINK "${_file}")
            message(FATAL_ERROR "Packed payload bytes missing or linked: ${_file}")
        endif()
        file(SIZE "${_file}" _size)
        file(SHA256 "${_file}" _digest)
        if(NOT _size EQUAL _stored_bytes OR NOT _digest STREQUAL _stored_sha256 OR NOT _size LESS raw_size)
            message(FATAL_ERROR "Packed payload byte integrity mismatch: ${_file}")
        endif()
        set(_codec true)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_metadata}" "${_file}")
    endif()
    set(${selected_file} "${_file}" PARENT_SCOPE)
    set(${selected_size} "${_size}" PARENT_SCOPE)
    set(${selected_codec} "${_codec}" PARENT_SCOPE)
endfunction()
